version: "3"

networks:
  default:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PROJECT_DIR}:/var/www/html/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${NGINX_LIB_DIR}:/etc/nginx/lib/:ro
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_VHOST_DIR}:/etc/nginx/conf.d/:ro
    restart: always
    networks:
      - default
    environment:
      TZ: "${TZ}"

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${TZ}"
    networks:
      - default

  php74:
    build:
      context: ./build/php/
      args:
        PHP_VERSION: ${PHP74_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP74_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php.sh
        TZ: "${TZ}"
    volumes:
      - ${PROJECT_DIR}:/var/www/html:rw
      - ${PHP74_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP74_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP74_LOG_DIR}:/var/log/php
      - ${COMPOSER_CACHE_DIR}:/usr/local/composer
      - ${COMPOSER_CONFIG_FILE}:/usr/local/composer/config.json
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  nodejs:
    image: node:alpine
    volumes:
      - ${PROJECT_DIR}:/var/www/html/:rw
